server:
  port: 7070

spring:
  application:
    name: 'Radio Alarm'

nitrite:
  database:
    file: 'radioalarm.db'

cors:
  allowed-origins: '*'
  allowed-methods: '*'
  allowed-headers: '*'
  allow-credentials: false